---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kina3126/public_html/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R upload $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp comproser.json $DEPLOYPATH
    - /bin/cp contributing.md $DEPLOYPATH
    - /bin/cp license.txt $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH