---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kina3126/public_html/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R upload $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH